name       : python-mypy_extensions
version    : 0.4.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/c2/92/3cc05d1206237d54db7b2565a58080a909445330b4f90a6436302a49f0f8/mypy_extensions-0.4.1.tar.gz : 37e0e956f41369209a3d5f34580150bcacfabaa57b33a15c0b25f4b5725e0812
license    : MIT
component  : programming.python
summary    : Experimental type system extensions for programs checked with the mypy typechecker
description: |
    The “mypy_extensions” module defines experimental extensions to the standard “typing” module
    that are supported by the mypy typechecker.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-mypy
build      : |
    %python3_setup
install    : |
    %python3_install
