name       : python-mypy_extensions
version    : 0.4.3
release    : 2
source     :
    - https://github.com/python/mypy_extensions/archive/0.4.3.tar.gz : 21e830f4baf996d0a9bd7048a5b23722dbd3b88354b8bf0e22376f9a8d508c16
license    : MIT
component  : programming.python
summary    : Experimental type system extensions for programs checked with the mypy typechecker
description: |
    The “mypy_extensions” module defines experimental extensions to the standard “typing” module
    that are supported by the mypy typechecker.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-mypy
build      : |
    %python3_setup
install    : |
    %python3_install
